[package]
name = "conways"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
tui-input = "0.7.1"
crossterm = "0.26.1"
rusqlite = "0.29.0"
fallible-iterator = "0.3.0"
